TransbankDevelopers/transbank-sdk-nodejs-example

src/components/questions/Questions.tsx
This PR adds the support team email.
=> feat: add support team mail

src/app/lib/webpay-mall/data.ts
This PR fix a problem when create transaction in Webpay mall.
=> fix: use mall credentials

src/app/invalid/invalidRefund.tsx, src/app/lib/webpay-mall-diferido/data.ts, src/app/lib/webpay-mall/data.ts, src/app/lib/webpay-plus/data.ts, src/app/webpay-mall-diferido/refund/page.tsx, src/app/webpay-mall/refund/page.tsx, src/app/webpay-plus-deferred/refund/page.tsx, src/app/webpay-plus/refund/page.tsx, src/components/customError/CustomError.tsx
This PR contains the following changes:
- View for possible errors in the reimbursement process.
- Modifications in the refund methods to handle errors.
- Redirection to the invalidRefund view in case of error.
>Before the changes
> After the changes
=> feat: add invalid refund page

src/app/oneclick-mall/content/snippets/create.ts
This PR fix the snippet code for Oneclick inscription.
=> fix: snippet for oneclick inscription

src/app/oneclick-mall/content/snippets/create.ts
This PR remove unused parameters and fix the build process.
=> fix: remove unused parameters

src/app/transaccion-completa-diferido/commit/page.tsx, src/app/transaccion-completa-mall-diferido/commit/page.tsx, src/app/transaccion-completa-mall/commit/page.tsx, src/app/transaccion-completa/commit/page.tsx, src/app/webpay-mall-diferido/commit/page.tsx, src/app/webpay-mall/commit/page.tsx, src/app/webpay-plus-deferred/commit/page.tsx, src/app/webpay-plus/commit/page.tsx
This PR update the commit content.
=> feat: update description for commit content

src/app/oneclick-mall-deferred/content/PageContent.tsx, src/app/oneclick-mall/content/PageContent.tsx, src/app/webpay-mall-diferido/page.tsx, src/app/webpay-mall/page.tsx, src/app/webpay-plus-deferred/page.tsx, src/app/webpay-plus/page.tsx, src/components/pageRefresh/PageRefresh.tsx
* reload 'Webpay Plus' and 'Oneclick' every 5 minutes
=> feat: add auto reload

src/app/webpay-mall-diferido/components/StatusButton.tsx
This PR: fix webpay mall deferred status button
=> fix: change 'onclick' to 'link'

src/app/api-reference/oneclick-mall-deferred/page.tsx, src/app/api-reference/oneclick-mall/page.tsx, src/app/api-reference/transaccion-completa-diferido/page.tsx, src/app/api-reference/transaccion-completa-mall-diferido/page.tsx, src/app/api-reference/transaccion-completa-mall/page.tsx, src/app/api-reference/transaccion-completa/page.tsx, src/app/api-reference/webpay-mall-deferred/page.tsx, src/app/api-reference/webpay-mall/page.tsx, src/app/api-reference/webpay-plus-deferred/page.tsx, src/app/api-reference/webpay-plus/page.tsx, src/app/transaccion-completa-diferido/content/steps/create.tsx, src/app/transaccion-completa-mall-diferido/content/steps/create.tsx, src/app/transaccion-completa-mall/content/steps/create.tsx, src/app/transaccion-completa/content/steps/create.tsx, src/components/sidebar/Sidebar.tsx, src/components/sidebar/SidebarItems.tsx
=> Feat: add more info

next.config.mjs, src/app/lib/oneclick-mall/data.tsx, src/app/oneclick-mall-deferred/components/StatusButton.tsx, src/app/oneclick-mall-deferred/refund/page.tsx, src/app/oneclick-mall/components/StatusButton.tsx, src/app/oneclick-mall/content/steps/status.tsx, src/app/oneclick-mall/refund/page.tsx, src/app/oneclick-mall/status/page.tsx, src/app/transaccion-completa-diferido/components/StatusButton.tsx, src/app/transaccion-completa-mall-diferido/components/StatusButton.tsx, src/app/transaccion-completa-mall-diferido/refund/page.tsx, src/app/transaccion-completa-mall/components/StatusButton.tsx, src/app/transaccion-completa-mall/refund/page.tsx, src/app/transaccion-completa/components/StatusButton.tsx, src/app/transaccion-completa/refund/page.tsx, src/app/webpay-mall-diferido/components/StatusButton.tsx, src/app/webpay-mall/components/StatusButton.tsx, src/app/webpay-plus-deferred/components/StatusButton.tsx, src/app/webpay-plus-deferred/refund/page.tsx, src/app/webpay-plus/components/StatusButton.tsx, src/app/webpay-plus/refund/page.tsx, src/components/button/Button.tsx
add satus  button in all refunds pages
=> Feat: status btn

src/app/lib/oneclick-mall/data.tsx, src/app/oneclick-mall-deferred/authorize/page.tsx, src/app/oneclick-mall-deferred/finish/content.tsx, src/app/oneclick-mall/authorize/page.tsx, src/app/oneclick-mall/finish/content.tsx, src/components/authorizeForm/AuthorizeForm.tsx, src/components/input/InputText.tsx
=> feat: authorize form

.gitignore, src/app/patpass-comercio/commit/page.tsx, src/app/patpass-comercio/voucher/page.tsx
This PR fix sonar issues.
Inscription Ok
=> fix: sonar issues

src/app/oneclick-mall-deferred/content/steps/authorize.tsx, src/app/oneclick-mall/content/steps/authorize.tsx, src/app/transaccion-completa-diferido/content/steps/commit.tsx, src/app/transaccion-completa-mall-diferido/content/steps/commit.tsx, src/app/transaccion-completa-mall/content/steps/commit.tsx, src/app/transaccion-completa/content/steps/commit.tsx, src/app/webpay-mall-diferido/content/steps/commit.tsx, src/app/webpay-mall/content/steps/commit.tsx, src/app/webpay-plus-deferred/content/steps/commit.tsx, src/app/webpay-plus/content/steps/commit.tsx, src/components/messages/OkAuthorizeMessage.tsx, src/components/messages/OkCommitMessage.tsx
This PR:
* update commit messages (Webpay and Transaccion Completa)
* update authorize messages (Oneclick Mall)
=> feat: update commit authorize message

CHANGELOG.md, package.json
=> release: prepare release 1.0.0

src/app/lib/webpay-mall-diferido/data.ts, src/app/lib/webpay-plus-deferred/data.ts, src/app/lib/webpay-plus/data.ts, src/app/webpay-plus-deferred/commit/page.tsx, src/app/webpay-plus-deferred/page.tsx, src/app/webpay-plus-deferred/refund/page.tsx, src/app/webpay-plus-deferred/status/page.tsx
This PR:
* Remove default options for Webpayplus Normal 
* Separate the Webpay Plus and Webpay Plus Deferred methods
=> feat: remove default options

src/app/oneclick-mall-deferred/content/snippets/create.ts, src/app/oneclick-mall/content/snippets/create.ts
This PR fix the redirection snippet for Oneclick
=> fix: oneclick redirection snippet

src/app/oneclick-mall-deferred/finish/error/aborted.tsx, src/app/oneclick-mall-deferred/finish/error/rejected.tsx, src/app/oneclick-mall-deferred/finish/error/timeout.tsx, src/app/oneclick-mall-deferred/page.tsx, src/app/oneclick-mall/authorize/page.tsx, src/app/oneclick-mall/finish/error/aborted.tsx, src/app/oneclick-mall/finish/error/rejected.tsx, src/app/oneclick-mall/finish/error/timeout.tsx, src/app/oneclick-mall/finish/page.tsx, src/app/oneclick-mall/page.tsx, src/app/oneclick-mall/refund/page.tsx, src/app/oneclick-mall/remove-user/page.tsx
This PR fix breadcrumb for Oneclick.
=> fix: Oneclick breadcrumb links

CHANGELOG.md, package-lock.json, package.json
=> release: prepare release 1.0.2

package.json, src/app/layout.tsx
Using component GoogleAnalytics from @next/third-parties library to connect project with GA
=> feat: add Google Analytics to project

.github/workflows/build.yml, CHANGELOG.md, package-lock.json, package.json, src/app/layout.tsx
=> release: prepare release 1.1.0
